-- ============================================================
-- RLS Policies — Personalisation & Newsletter
-- (user_preferences, user_interactions, recommendations,
--  newsletter_subscriptions)
-- ============================================================
-- The simplest group: no draft/published logic, no payment
-- sensitivity. Each table just needs "you see and manage your
-- own data, staff sees everyone's."
--
-- The one exception: user_interactions needs an INSERT policy
-- for regular users, not just SELECT — this table exists to log
-- what a visitor views/searches/clicks as they browse, which is
-- the entire input the recommendation system runs on. Without
-- insert access, the app could never record behaviour in the
-- first place.
--
-- recommendations, by contrast, gets NO insert/update policy for
-- users — those rows are generated by your recommendation logic
-- (likely a scheduled job or backend process using the service
-- role), not written by the visitor directly.
-- ============================================================


-- --------------------------------------------------------------
-- user_preferences (onboarding interest picks)
-- --------------------------------------------------------------

create policy "user_preferences_select_own"
on user_preferences for select
using (auth.uid() = user_id);

create policy "user_preferences_insert_own"
on user_preferences for insert
with check (auth.uid() = user_id);

create policy "user_preferences_update_own"
on user_preferences for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "user_preferences_delete_own"
on user_preferences for delete
using (auth.uid() = user_id);

create policy "user_preferences_staff_all"
on user_preferences for all
using (public.is_staff())
with check (public.is_staff());


-- --------------------------------------------------------------
-- user_interactions (behaviour log — needs insert, not just read)
-- --------------------------------------------------------------

create policy "user_interactions_select_own"
on user_interactions for select
using (auth.uid() = user_id);

create policy "user_interactions_insert_own"
on user_interactions for insert
with check (auth.uid() = user_id);

create policy "user_interactions_staff_all"
on user_interactions for all
using (public.is_staff())
with check (public.is_staff());


-- --------------------------------------------------------------
-- recommendations (generated by the system, read-only for users)
-- --------------------------------------------------------------

create policy "recommendations_select_own"
on recommendations for select
using (auth.uid() = user_id);

create policy "recommendations_staff_all"
on recommendations for all
using (public.is_staff())
with check (public.is_staff());


-- --------------------------------------------------------------
-- newsletter_subscriptions
-- --------------------------------------------------------------

create policy "newsletter_select_own"
on newsletter_subscriptions for select
using (auth.uid() = user_id);

create policy "newsletter_insert_own"
on newsletter_subscriptions for insert
with check (auth.uid() = user_id);

create policy "newsletter_update_own"
on newsletter_subscriptions for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "newsletter_staff_all"
on newsletter_subscriptions for all
using (public.is_staff())
with check (public.is_staff());
